CREATE TABLE characters(
	id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  bounty VARCHAR(255) NULL,
  status VARCHAR(255) NULL,
  devil_fruit VARCHAR(255),
  crew VARCHAR(255) NULL,
  quote VARCHAR(500) NULL,
  img_thumbnail VARCHAR(255) NULL,
  img VARCHAR(255) NULL
);

INSERT INTO
  characters (name, bounty, status, devil_fruit, crew, quote, img_thumbnail, img)
VALUES
    ('Yamato', '฿-Unknown', 'Alive', 'Inu Inu:Okuchi no Makami model','Beasts Pirates', 'I can not believe it! That cow-gorilla! He was really going to kill me! That makes it clear! I will no longer see him as my father!! (Yamato denies his father)', 'assets/img/thumbnails/yamato-thumbnail.png', 'assets/img/yamato.png'),
    ('Gol D. Roger', '฿5,564,800,000','Deceased', NULL,'Roger Pirates', 'Wealth, fame, power ... The man who achieved everything in this world, the King of the Pirates "Gold Roger." The last words he said just before he died sent many people to the seas.', 'assets/img/thumbnails/roger-thumbnail.png', 'assets/img/roger.jpg'),
    ('Edward Newgate', '฿5,046,000,000', 'Deceased', 'Gura Gura no Mi','Whitebeard Pirates', 'Whitebeard is ... That man is ... The only one who could fight at the same level as Gold Roger ... Undoubtedly, today, he is the strongest pirate in the world and the man closest to getting the One Piece!', 'assets/img/thumbnails/edward-newgate-thumbnail.png', 'assets/img/whitebeard.jpg'),
    ('Kaidou', '฿4,611,100,000', 'Alive', 'Uo Uo: seiryu model','Beasts Pirates', 'He has been captured by the Marines and the Emperors of the Sea eighteen times. He has been tortured a thousand times and sentenced to death 40 times. When they tried to hang him, the chains would break, when they used the guillotine, the blade would break (...) In other words; no one has ever been able to kill him.', 'assets/img/thumbnails/kaidou-thumbnail.png', 'assets/img/kaidou.jpg'),
    ('Charlotte Linlin', '฿4,388,000,000', 'Alive', 'Soru Soru','Big Mom Pirates', 'Those who don''t give us sweets will be dyed red ... I don''t like people who promise you something but then don''t give it to you. I hate them as much as sour sweets ...', 'assets/img/thumbnails/charlotte-linlin-thumbnail.png', 'assets/img/bigmom.png'),
    ('Shanks', '฿4,048,900,000', 'Alive',NULL,'Redhead Pirates', 'No one will be able to stop the wave of this wild age!', 'assets/img/thumbnails/shanks-thumbnail.png', 'assets/img/shanks.jpg'),
    ('Marshall D. Teach', '฿2,247,600,000', 'Alive','Yami Yami no Mi | Gura Gura no Mi','Blackbeard Pirates', 'Is the Age of Pirates Dreaming Over ?! Eh? People''s dreams ... never end!', 'assets/img/thumbnails/blackbeard-thumbnail.png', 'assets/img/blackbeard.jpg'),
    ('Monkey D. Luffy', '฿1,500,000,000', 'Alive', 'Gomu Gomu no Mi','Straw Hat Pirates', 'I will be the future king of pirates', 'assets/img/thumbnails/luffy-thumbnail.png', 'assets/img/luffy.jpg'),
    ('King', '฿1,390,000,000', 'Alive', NULL,'Beasts Pirates', NULL, 'assets/img/thumbnails/king-thumbnail.png', 'assets/img/king.png'),
    ('Marco', '฿1,374,000,000', 'Alive', 'Tori Tori no Mi, Model Phoenix','Whitebeard Pirates', 'You cannot defeat the king ... on the first move.', 'assets/img/thumbnails/marco-thumbnail.png', 'assets/img/marco.jpg'),
    ('Queen', '฿1,320,000,000', 'Alive', 'Ryu Ryu no Mi, Model: Brachiosaurus','Beasts Pirates', 'You pleasures had a chance to gain useful skills, but you lost that bet! Now you are only good enough to laugh! And you waiters ! No matter how long you wait, no more SMILEs are coming! You have missed the opportunity to acquire skills! You will be waiters forever! You losers can only be of use to the almighty Beast Pirates ... by turning into ice onis now!', 'assets/img/thumbnails/queen-thumbnail.png', 'assets/img/queen.png'),
    ('Charlotte Katakuri', '฿1,057,000,000', 'Alive', NULL,'Big Mom Pirates', 'My brother Katakuri is a "superhuman", the perfect man, the greatest creation of the Charlotte family!', 'assets/img/thumbnails/charlotte-katakuri-thumbnail.png', 'assets/img/katakuri.jpg'),
    ('Jack', '฿1,000,000,000', 'Alive', 'Zou Zou no Mi, Model: Mammoth','Beasts Pirates', 'All the land you walk on remains arid as if it had suffered a drought!!!', 'assets/img/thumbnails/jack-thumbnail.png', 'assets/img/jack.jpg'),
    ('Charlotte Smoothie', '฿932,000,000', 'Alive', 'Shibo Shibo no Mi','Big Mom Pirates', NULL, 'assets/img/thumbnails/charlotte-smoothie-thumbnail.png', 'assets/img/smoothie.jpg'),
    ('Charlotte Cracker', '฿860,000,000', 'Alive', 'Bisu Bisu no Mi','Big Mom Pirates', 'There will always be someone better than you no matter how hard you try. Understanding this is true "maturity", you brat!!', 'assets/img/thumbnails/charlotte-cracker-thumbnail.png', 'assets/img/cracker.jpg'),
    ('Charlotte Perospero', '฿700,000,000', 'Alive', 'Pero Pero no Mi','Big Mom Pirates', 'If it takes you longer than agreed, I''ll make you a "candy man" to suck on', 'assets/img/thumbnails/charlotte-perospero-thumbnail.png', 'assets/img/perospero.png'),
    ('Sabo', '฿602,000,000', 'Unknown', 'Mera Mera no Mi','Revolutionary Army', NULL, 'assets/img/thumbnails/sabo-thumbnail.png', 'assets/img/sabo.jpg'),
    ('Charlotte Snack', '฿600,000,000', 'Alive', NULL,'Big Mom Pirates', NULL, 'assets/img/thumbnails/charlotte-snack-thumbnail.png', 'assets/img/snack.png'),
    ('Little Oars Jr', '฿550,000,000', NULL, NULL,'Little Pirates', NULL, 'assets/img/oarsjr.png', 'assets/img/oarsjr.png'),
    ('Portgas D. Ace', '฿550,000,000', 'Deceased', 'Mera Mera no Mi','Whitebeard Pirates', 'Their fists of fire were known to sink great warships and reduce the mightiest cities into a fiery living hell ...', 'assets/img/thumbnails/portgas-d-ace-thumbnail.png', 'assets/img/ace.jpg'),
    ('Who''s-Who', '฿546,000,000', NULL, NULL,'Beasts Pirates', NULL, 'assets/img/thumbnails/whos-who-thumbnail.png', 'assets/img/whoswho.png'),
    ('Izou', '฿510,000,000', 'Alive', NULL,'Whitebeard Pirates', NULL, 'assets/img/thumbnails/izou-thumbnail.png', 'assets/img/izou.png'),
    ('Trafalgar D. Water Law', '฿500,000,000', 'Alive', 'Ope Ope no Mi','Heart Pirates', 'It''s that North Blue they pay ฿200,000,000 bounty for ... Trafalgar Law. I''ve heard quite a few bad things about him. On top of that, he has bad manners ...', 'assets/img/thumbnails/trafalgar-thumbnail.png', 'assets/img/trafalgar.jpg'),
    ('Black Maria', '฿480,000,000', 'Alive', 'Kumo Kumo no Mi, Model: Rosamygale Grauvogeli','Beasts Pirates', NULL, 'assets/img/thumbnails/black-maria-thumbnail.png', 'assets/img/blackmaria.png'),
    ('Edward Weevil', '฿480,000,000', 'Alive', NULL,'Seven Warlords of the Sea', 'He is a pirate whose powers should be feared. It''s like looking at a younger version of Whitebeard , at least in strength ...', 'assets/img/thumbnails/edward-weevil-thumbnail.png', 'assets/img/edwardweevil.png'),
    ('Eustass Kid', '฿470,000,000', 'Alive', 'Jiki Jiki no Mi','Kid Pirates', 'On the route we took, people laughed at us for saying something like that (wanting to get the One Piece). However ... he killed everyone who dared to laugh ... !! But from here on, we enter a sea where anyone who does not have the courage to say so is Dead. Let''s meet again in the New World !!', 'assets/img/thumbnails/kid-thumbnail.png', 'assets/img/kid.jpg'),
    ('Belo Betty', '฿457,000,000', 'Alive', 'Kobu Kobu no Mi','Revolutionary Army', 'We will never turn our backs on the weak who rise up.', 'assets/img/thumbnails/belo-betty-thumbnail.png', 'assets/img/belobetty.jpg'),
    ('Jinbe', '฿438,000,000', 'Alive', NULL,'Straw Hat Pirates', 'It may be hard right now... But you must silence those thoughts! Stop counting only those things that you have lost! What is gone, is gone! So ask yourself this: What is there... that still remains to you?!', 'assets/img/thumbnails/jinbe-thumbnail.png', 'assets/img/jimbe.png'),
    ('Ulti', '฿400,000,000', 'Alive', 'Ryu Ryu no Mi, Model: Pachycephalosaurus','Beasts Pirates', NULL, 'assets/img/thumbnails/ulti-thumbnail.png', 'assets/img/ulti.jpg'),
    ('Donquixote Doflamingo', '฿340,000,000', 'Alive', 'Ito Ito no Mi','Donquixote Pirates', 'The weaker person is the more he gets hung up on other people''s pain and then he self-destructs', 'assets/img/thumbnails/doflamingo-thumbnail.png', 'assets/img/doflamingo.jpg'),
    ('Vinsmoke Sanji', '฿330,000,000', 'Alive', NULL,'Straw Hat Pirates', NULL, 'assets/img/thumbnails/sanji-thumbnail.png', 'assets/img/sanji.jpg'),
    ('Basil Hawkins', '฿320,000,000', 'Alive', 'Wara Wara no Mi','Hawkins Pirates', 'As for your clothes ... I''m sorry to tell you that was her destiny. Taking a life today is a bad omen.', 'assets/img/thumbnails/basil-hawkins-thumbnail.png', 'assets/img/basilhawkins.png'),
    ('Gecko Moria', '฿320,000,000', 'Alive', 'Kage Kage no Mi','Thriller Bark Pirates', NULL, 'assets/img/thumbnails/gecko-moria-thumbnail.png', 'assets/img/gecko.png'),
    ('Roronoa Zoro', '฿320,000,000', 'Alive', NULL,'Straw Hat Pirates', 'Being strong isn''t just about having power or move, it about one''s spirit', 'assets/img/thumbnails/zoro-thumbnail.png', 'assets/img/zoro.jpg'),
    ('Lindbergh', '฿316,000,000', 'Alive', NULL,'Revolutionary Army', NULL, 'assets/img/thumbnails/lindbergh-thumbnail.png', 'assets/img/lindbergh.jpg'),
    ('Caesar Clown', '฿300,000,000', 'Alive', 'Gasu Gasu no Mi','Donquixote Pirates', NULL, 'assets/img/caesar.jpg', 'assets/img/caesar.jpg'),
    ('Bartholomew Kuma', '฿296,000,000','Alive', 'Nikyu Nikyu no Mi','Revolutionary Army', NULL, 'assets/img/thumbnails/bartholomew-kuma-thumbnail.png', 'assets/img/kuma.jpg'),
    ('Page One', '฿290,000,000', 'Alive', 'Ryu Ryu no Mi, Model: Spinosaurus','Beasts Pirates', NULL, 'assets/img/thumbnails/page-one-thumbnail.png', 'assets/img/pageone.png'),
    ('X Drake', '฿222,000,000', 'Alive', 'Ryu Ryu no Mi, Model: Allosaurus',NULL, NULL, 'assets/img/thumbnails/drake-thumbnail.png', 'assets/img/drake.jpg'),
    ('Usopp', '฿200,000,000', 'Alive', NULL,'Straw Hat Pirates', 'Man or Child, Strong or Weak, None of those matter once you are out at sea!', 'assets/img/thumbnails/usopp-thumbnail.png', 'assets/img/ussop.jpg'),
    ('Jewelry Bonney', '฿140,000,000', 'Alive', 'unknown',NULL, NULL, 'assets/img/thumbnails/jewelry-bonney-thumbnail.png', 'assets/img/jewelrybonney.jpg'),
    ('Nico Robin', '฿130,000,000', 'Alive', 'Hana Hana no Mi','Straw Hat Pirates', NULL, 'assets/img/thumbnails/nico-robin-thumbnail.png', 'assets/img/nico-robin.jpg'),
    ('Brogy', '฿100,000,000', 'Alive', NULL,'Giant Warrior Pirates', NULL, 'assets/img/thumbnails/brogy-thumbnail.png', 'assets/img/brogy.png'),
    ('Franky', '฿94,000,000', 'Alive' ,NULL,'Straw Hat Pirates', NULL, 'assets/img/thumbnails/franky-thumbnail.png', 'assets/img/franky.png'),
    ('Crocodile', '฿81,000,000', 'Alive', 'Suna Suna no Mi','Baroque Works', NULL, 'assets/img/thumbnails/crocodile-thumbnail.png', 'assets/img/crocodile.jpg'),
    ('Boa Hancock', '฿80,000,000', 'Alive', 'Mero Mero no Mi','Kuja Pirates', NULL, 'assets/img/thumbnails/boa-hancock-thumbnail.png', 'assets/img/boahancock.jpg'),
    ('Nami', '฿66,000,000', 'Alive', NULL,'Straw Hat Pirates', NULL, 'assets/img/thumbnails/nami-thumbnail.png', 'assets/img/nami.jpg'),
    ('Van Augur', '฿64,000,000', 'Alive', NULL,'Blackbeard Pirates', NULL, 'assets/img/thumbnails/van-augur-thumbnail.png', 'assets/img/vanaugur.png'),
    ('Laffitte', '฿42,200,000', 'Alive', '(unknown)','Blackbeard Pirates', NULL, 'assets/img/thumbnails/laffitte-thumbnail.png', 'assets/img/laffitte.jpg'),
    ('Bentham', '฿32,000,000', 'Alive', 'Mane Mane no Mi','Baroque Works', NULL, 'assets/img/thumbnails/bentham-thumbnail.png', 'assets/img/bentham.jpg'),
    ('Marianne', '฿29,000,000', 'Alive', NULL,'Baroque Works', NULL, 'assets/img/thumbnails/marianne-thumbnail.png', 'assets/img/marianne.jpg'),
    ('Demaro Black', '฿26,000,000', 'Alive', NULL,'Fake Straw Hat crew', NULL, 'assets/img/thumbnails/demalo-black-thumbnail.png', 'assets/img/demaroblack.png'),
    ('Foxy', '฿24,000,000', 'Alive', 'Noro Noro no Mi','Foxy Pirates', NULL, 'assets/img/thumbnails/foxy-thumbnail.png', 'assets/img/foxy.jpg'),
    ('Galdino', '฿24,000,000', 'Alive', 'Doru Doru no Mi','Buggy Pirates', NULL, 'assets/img/thumbnails/galdino-thumbnail.png', 'assets/img/galdino.png'),
    ('Arlong', '฿20,000,000', 'Alive', NULL,'Arlong Pirates', NULL, 'assets/img/thumbnails/arlong-thumbnail.png', 'assets/img/arlong.png'),
    ('Jesus Burgess', '฿20,000,000', 'Alive', NULL,'Blackbeard Pirates', NULL, 'assets/img/thumbnails/jesus-burgess-thumbnail.png', 'assets/img/jesusburgess.png'),
    ('Buggy', '฿15,000,000', 'Alive', 'Bara Bara no Mi','Buggy Pirates', NULL, 'assets/img/thumbnails/buggy-thumbnail.png', 'assets/img/buggy.jpg'),
    ('Hatchan', '฿8,000,000', 'Alive', NULL,'Arlong Pirates', NULL, 'assets/img/thumbnails/hatchan-thumbnail.png', 'assets/img/hatchan.png'),
    ('Curly Dadan', '฿7,800,000', 'Alive', NULL,'Bandits', NULL, 'assets/img/thumbnails/curly-dadan-thumbnail.png', 'assets/img/curlydadan.png'),
    ('Buchi', '฿7,000,000', 'Alive', NULL,'Black Cat Pirates', NULL, 'assets/img/thumbnails/buchi-thumbnail.png', 'assets/img/buchi.png'),
    ('Sham', '฿7,000,000', 'Alive', NULL,'Black Cat Pirates', NULL, 'assets/img/thumbnails/sham-thumbnail.png', 'assets/img/sham.png'),
    ('Alvida', '฿5,000,000', 'Alive', 'Sube Sube no Mi','Buggy Pirates', 'Tell me, who is the most beautiful woman in all the seas?', 'assets/img/thumbnails/alvida-thumbnail.png', 'assets/img/alvida.jpg'),
    ('Bepo', '฿500', 'Alive', NULL,'Heart Pirates', NULL, 'assets/img/thumbnails/bepo-thumbnail.png', 'assets/img/bepo.jpg'),
    ('Tony Tony Chopper', '฿100', 'Alive', 'Hito Hito no Mi','Straw Hat Pirates', NULL, 'assets/img/thumbnails/tony-tony-chopper-thumbnail.png', 'assets/img/chopper.jpg'),
    ('Yasopp', '฿-Unknown', 'Alive', NULL,'Redhead Pirates', NULL, 'assets/img/thumbnails/yasopp-thumbnail.png', 'assets/img/yasopp.jpg'),
    ('Silvers Rayleigh', ' ฿-Unknown', 'Alive', NULL,'Roger Pirates', NULL, 'assets/img/thumbnails/silvers-rayleigh-thumbnail.png', 'assets/img/silversrayleigh.jpg'),
    ('Dracule Mihawk', '฿-Unknown', 'Alive', NULL,'Seven Warlords of the Sea',  'When a man lets go of his pride, it is always for someone else.', 'assets/img/thumbnails/dracule-mihawk-thumbnail.png', 'assets/img/draculemihawk.png'),
    ('Kozuki Oden', '฿-Unknown', 'Deceased', NULL,'Roger Pirates', 'I''m Oden! And I was born to boil!', 'assets/img/thumbnails/kozuki-oden-thumbnail.png', 'assets/img/kozukioden.png'),
    ('Joy Boy', '฿-Unknown','Unknown', NULL,'Unknown', NULL, 'assets/img/unknown-joy-boy.png', 'assets/img/unknown-joy-boy.png'),
    ('Scopper Gaban', '฿-Unknown','Unknown', NULL,'Roger Pirates', NULL, 'assets/img/thumbnails/scopper-gaban-thumbnail.png', 'assets/img/scopper-gaban.png'),
	  ('Crocus', 'Unknown','Unknown', NULL,'Roger Pirates', NULL, 'assets/img/thumbnails/crocus-thumbnail.png', 'assets/img/crocus.png');


SELECT * FROM characters;